#!/usr/bin/with-contenv bash

if [ ! -f /config/nginx/site-confs/healthcheck ]; then
  cp /defaults/healthcheck /config/nginx/site-confs/healthcheck
fi

if [[ $(grep -c 'listen 8080' /config/nginx/site-confs/healthcheck) -eq 0 ]]; then
  echo "Updating listen on healthcheck"
  sed -i -e 's|listen [0-9]*;|listen 8080;|' /config/nginx/site-confs/healthcheck
fi

# Copy over modified default site file
if [ ! -f /config/nginx/site-confs/.default.rework ]; then
  echo '--------------------------------------'
  echo '|      Backing up default file       |'
  echo '--------------------------------------'
  mv /config/nginx/site-confs/default /config/nginx/site-confs/.default.rework
else
  :
fi

if [ -f /config/nginx/site-confs/default ]; then
  echo '--------------------------------------'
  echo '|      Copying default site file     |'
  echo '--------------------------------------'
  cp /defaults/default /config/nginx/site-confs/default
else
  :
fi

if [[ $(grep -c "# V0.0." /config/nginx/site-confs/default) -eq 0 && $(grep -c "# V0.0.X" /config/nginx/site-confs/default) -eq 0 ]]; then
  mv /config/nginx/site-confs/default /config/nginx/site-confs/.default.rework2
  cp /defaults/default /config/nginx/site-confs/default
fi

# Check for the fastcgi_hide_header line and,
# if it does not exist, add it
if [[ $(grep -c fastcgi_hide_header /config/nginx/site-confs/default) -eq 0 ]]; then
  sed -i $'s|include /etc/nginx/fastcgi_params;|include /etc/nginx/fastcgi_params;\\\n    fastcgi_hide_header X-Powered-By;|g' /config/nginx/site-confs/default
elif [[ $(grep -c fastcgi_hide_header /config/nginx/site-confs/default) -ge 1 ]]; then
  :
fi

# Check for the try_files line for CVE-2019-11043 and,
# if it does not exist, add it
if [[ $(grep -c try_files /config/nginx/site-confs/default) -eq 1 ]]; then
  sed -i $'s|fastcgi_split_path_info \^(\.+\\\.php)(\/\.+)\$;|fastcgi_split_path_info \^(\.+\\\.php)(\/\.+)\$;\\\n    try_files $fastcgi_script_name =404;|g' /config/nginx/site-confs/default
elif [[ $(grep -c try_files /config/nginx/site-confs/default) -ge 2 ]]; then
  :
fi

# permissions
chown -R abc:abc \
	/config \
	/var/lib/nginx \
	/var/tmp/nginx
chmod -R g+w \
	/config/{nginx,www}
chmod -R 644 /etc/logrotate.d